version: '3.8'

services:
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - dbdata:/data/db

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}

volumes:
  dbdata:
